[[plugins]]  # Python用オートコンプリートプラグイン jedi-vim
# ...導入前に確認しておきたいこと
# この記事を参照 https://wonderwall.hatenablog.com/entry/2017/01/29/213052
repo = 'davidhalter/jedi-vim'
on_ft = ['python']



[[plugins]]  # オートコンプリートプラグイン
# この辺を参考に作る
# https://www.karakaram.com/neocomplcache#install-vimproc
# 一部のファイルを開いた時のみ対応する
repo = 'Shougo/neocomplete.vim'
on_ft = ['python', 'c']
hook_add = '''
""" 一般設定 """
"  自動ポップアップ (0:無効 1:有効)
" let g:acp_enableAtStartup = 0
"  neocompleteの使用 (0:無効 1:有効)
let g:neocomplete#enable_at_startup=1
" スマートケースの利用 (0:無効 1:有効)
let g:neocomplete#enable_smart_case=1
"  ポップアップで表示される候補の数
let g:neocomplete#max_list = 10
"  キーワードの長さ
let g:neocomplete#max_keyword_width = 80
"  大文字小文字を無視して候補を出す (0:無効 1:有効)
let g:neocomplete#enable_ignore_case = 1
"  補完候補の出力に必要なキーワードの数
let g:neocomplete#sources#syntax#min_keyword_lenth=1
"  補完時に画面上部に出てくるdocstringを非表示にする
autocmd FileType python setlocal completeopt-=preview

""" キーマッピング """
inoremap <expr><C-g> neocomplete#undo_completion()
inoremap <expr><C-l> neocomplete#complete_common_string()
inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><CR> pumvisible() ? "\<C-y>" : "\<CR>"
inoremap <expr><C-n> pumvisible() ? "\<C-n>" : "\<C-x>\<C-u>\<C-p>"
inoremap <expr><C-c> neocomplete#cancel_popup()
inoremap <expr><C-u> neocomplete#undo_completion()
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"

" 文字を入力するたびに補完を表示(特定言語のみ適応)
function! LiveComplete()
    for k in split("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_",'\zs')
    exec "inoremap <expr> " . k . " pumvisible() ? '" . k . "' : '" . k . "\<C-X>\<C-O>\<C-P>'"
    endfor
endfunction
autocmd FileType python call LiveComplete()
autocmd FileType c call LiveComplete()

""" 各言語との連携 """
autocmd FileType python setlocal omnifunc=jedi#completions
let g:jedi#auto_vim_configuration = 0

"  オムニ補完の有効化(遅くなる)
if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
endif

let g:neocomplete#force_omni_input_patterns.python = '\h\w*\|[^. \t]\.\w*'

'''

